const crypto = require("crypto");

// Helper function to generate random dates
const randomDate = (start, end) => {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
};

// Helper function to create hash
const createHash = (data) => {
  return crypto.createHash("sha256").update(JSON.stringify(data)).digest("hex");
};

// Seed data for Clubs (NGOs)
const clubsData = [
  {
    name: "Harit Bharat Foundation",
    email: "contact@haritbharat.org",
    password: "$2b$10$YourHashedPasswordHere",
    userName: "haritbharat",
    tagLine: "Protecting our motherland for future generations",
    description: "Harit Bharat Foundation is dedicated to environmental conservation, reforestation, and climate change mitigation across India. We work with local panchayats to create sustainable solutions.",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    pincode: "110001",
    address: "123 Green Park, Suite 400",
    website: "https://haritbharat.org",
    iframe: "https://maps.google.com/maps?q=new+delhi&output=embed",
  },
  {
    name: "Asha Bal Vikas",
    email: "info@ashabalvikas.org",
    password: "$2b$10$YourHashedPasswordHere",
    userName: "ashabalvikas",
    tagLine: "Every child deserves a bright future",
    description: "Asha Bal Vikas provides education, healthcare, and protection to underprivileged children across rural India. We believe in empowering the next generation.",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    pincode: "400001",
    address: "45 Marine Lines",
    website: "https://ashabalvikas.org",
    iframe: "https://maps.google.com/maps?q=mumbai&output=embed",
  },
  {
    name: "Swasthya Seva Sangh",
    email: "hello@swasthyaseva.org",
    password: "$2b$10$YourHashedPasswordHere",
    userName: "swasthyaseva",
    tagLine: "Healthcare for all, regardless of circumstances",
    description: "We provide free medical services, health education, and preventive care to underserved communities. Our mobile clinics reach remote villages with essential healthcare.",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    address: "78 MG Road",
    website: "https://swasthyaseva.org",
    iframe: "https://maps.google.com/maps?q=bangalore&output=embed",
  },
  {
    name: "Digital India Initiative",
    email: "team@digitalindia.org",
    password: "$2b$10$YourHashedPasswordHere",
    userName: "digitalindia",
    tagLine: "Bridging the digital divide",
    description: "Digital India Initiative teaches coding, digital literacy, and technology skills to youth in developing regions. We provide computers and internet access to government schools.",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    pincode: "500001",
    address: "22 Hitech City",
    website: "https://digitalindia.org",
    iframe: "https://maps.google.com/maps?q=hyderabad&output=embed",
  },
  {
    name: "Jiv Daya Sanstha",
    email: "rescue@jivdaya.org",
    password: "$2b$10$YourHashedPasswordHere",
    userName: "jivdaya",
    tagLine: "Giving voice to the voiceless",
    description: "Jiv Daya Sanstha saves abandoned and abused animals, provides veterinary care, and finds loving homes. We also work on wildlife conservation projects.",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    pincode: "600001",
    address: "567 Anna Salai",
    website: "https://jivdaya.org",
    iframe: "https://maps.google.com/maps?q=chennai&output=embed",
  },
  {
    name: "Nirmal Jal Yojana",
    email: "info@nirmaljal.org",
    password: "$2b$10$YourHashedPasswordHere",
    userName: "nirmaljal",
    tagLine: "Pure water, healthy communities",
    description: "We build wells, install filtration systems, and provide clean drinking water to communities lacking access. Over 2 million people served nationwide.",
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    pincode: "700001",
    address: "101 Park Street",
    website: "https://nirmaljal.org",
    iframe: "https://maps.google.com/maps?q=kolkata&output=embed",
  },
  {
    name: "Vidya Prasar Samiti",
    email: "contact@vidyaprasar.org",
    password: "$2b$10$YourHashedPasswordHere",
    userName: "vidyaprasar",
    tagLine: "Opening doors through reading",
    description: "Vidya Prasar Samiti builds libraries, trains teachers, and provides books to children in rural areas. We've established over 500 community libraries.",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    pincode: "411001",
    address: "88 FC Road",
    website: "https://vidyaprasar.org",
    iframe: "https://maps.google.com/maps?q=pune&output=embed",
  },
  {
    name: "Aapda Rahat Dal",
    email: "emergency@aapdarahat.org",
    password: "$2b$10$YourHashedPasswordHere",
    userName: "aapdarahat",
    tagLine: "First responders in times of crisis",
    description: "Rapid response to natural disasters providing emergency shelter, food, medical aid, and rebuilding support. Active in all states.",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    pincode: "380001",
    address: "33 Ashram Road",
    website: "https://aapdarahat.org",
    iframe: "https://maps.google.com/maps?q=ahmedabad&output=embed",
  },
];

// Seed data for Events
const eventsData = [
  {
    name: "Annual Charity Gala 2025",
    uid: "evt_" + crypto.randomBytes(8).toString("hex"),
    description: "Join us for an elegant evening of fundraising, entertainment, and networking. All proceeds support environmental conservation projects across India.",
    hostUsername: "haritbharat",
    hostName: "Harit Bharat Foundation",
    coverImage: "https://images.unsplash.com/photo-1540575467063-178a50c2df87",
    mode: "Offline",
    address: "Grand Ballroom, Taj Palace",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    mapIframe: "https://maps.google.com/maps?q=taj+palace+new+delhi&output=embed",
    platform: "",
    platformLink: "",
    startDate: new Date("2025-03-15"),
    endDate: new Date("2025-03-15"),
    startTime: new Date("2025-03-15T19:00:00"),
    endTime: new Date("2025-03-15T23:00:00"),
  },
  {
    name: "Virtual Tech Workshop: Coding for Kids",
    uid: "evt_" + crypto.randomBytes(8).toString("hex"),
    description: "Free online workshop teaching basic programming to children ages 8-14. Interactive sessions with hands-on projects.",
    hostUsername: "digitalindia",
    hostName: "Digital India Initiative",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b",
    mode: "Online",
    address: "",
    city: "",
    state: "",
    country: "",
    mapIframe: "",
    platform: "Zoom",
    platformLink: "https://zoom.us/j/workshop2025",
    startDate: new Date("2025-02-20"),
    endDate: new Date("2025-02-20"),
    startTime: new Date("2025-02-20T10:00:00"),
    endTime: new Date("2025-02-20T14:00:00"),
  },
  {
    name: "Community Health Mela",
    uid: "evt_" + crypto.randomBytes(8).toString("hex"),
    description: "Free health screenings, consultations, and wellness education. Bring your family for a day of health awareness.",
    hostUsername: "swasthyaseva",
    hostName: "Swasthya Seva Sangh",
    coverImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d",
    mode: "Offline",
    address: "Shivaji Park",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    mapIframe: "https://maps.google.com/maps?q=shivaji+park+mumbai&output=embed",
    platform: "",
    platformLink: "",
    startDate: new Date("2025-04-10"),
    endDate: new Date("2025-04-10"),
    startTime: new Date("2025-04-10T08:00:00"),
    endTime: new Date("2025-04-10T17:00:00"),
  },
  {
    name: "Tree Planting Mahotsav",
    uid: "evt_" + crypto.randomBytes(8).toString("hex"),
    description: "Help us plant 10,000 trees in one day! Volunteers of all ages welcome. Tools and refreshments provided.",
    hostUsername: "haritbharat",
    hostName: "Harit Bharat Foundation",
    coverImage: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09",
    mode: "Offline",
    address: "Lodhi Gardens",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    mapIframe: "https://maps.google.com/maps?q=lodhi+gardens&output=embed",
    platform: "",
    platformLink: "",
    startDate: new Date("2025-05-22"),
    endDate: new Date("2025-05-22"),
    startTime: new Date("2025-05-22T07:00:00"),
    endTime: new Date("2025-05-22T16:00:00"),
  },
  {
    name: "Pet Adoption Drive",
    uid: "evt_" + crypto.randomBytes(8).toString("hex"),
    description: "Meet your new best friend! Over 100 rescued animals looking for forever homes. Adoption fees waived.",
    hostUsername: "jivdaya",
    hostName: "Jiv Daya Sanstha",
    coverImage: "https://images.unsplash.com/photo-1450778869180-41d0601e046e",
    mode: "Offline",
    address: "Chennai Trade Centre",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    mapIframe: "https://maps.google.com/maps?q=chennai+trade+centre&output=embed",
    platform: "",
    platformLink: "",
    startDate: new Date("2025-03-08"),
    endDate: new Date("2025-03-09"),
    startTime: new Date("2025-03-08T10:00:00"),
    endTime: new Date("2025-03-09T18:00:00"),
  },
  {
    name: "National Education Webinar",
    uid: "evt_" + crypto.randomBytes(8).toString("hex"),
    description: "Expert panel discussion on improving education in rural India. Open to educators, policymakers, and the public.",
    hostUsername: "ashabalvikas",
    hostName: "Asha Bal Vikas",
    coverImage: "https://images.unsplash.com/photo-1523580494863-6f3031224c94",
    mode: "Online",
    address: "",
    city: "",
    state: "",
    country: "",
    mapIframe: "",
    platform: "Microsoft Teams",
    platformLink: "https://teams.microsoft.com/education-webinar",
    startDate: new Date("2025-06-15"),
    endDate: new Date("2025-06-15"),
    startTime: new Date("2025-06-15T14:00:00"),
    endTime: new Date("2025-06-15T16:30:00"),
  },
  {
    name: "Water Well Inauguration Ceremony",
    uid: "evt_" + crypto.randomBytes(8).toString("hex"),
    description: "Celebrate the completion of our 100th water well project. Join the community celebration with local performances.",
    hostUsername: "nirmaljal",
    hostName: "Nirmal Jal Yojana",
    coverImage: "https://images.unsplash.com/photo-1559827260-dc66d52bef19",
    mode: "Offline",
    address: "Salt Lake City",
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    mapIframe: "https://maps.google.com/maps?q=salt+lake+city+kolkata&output=embed",
    platform: "",
    platformLink: "",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-01"),
    startTime: new Date("2025-07-01T11:00:00"),
    endTime: new Date("2025-07-01T15:00:00"),
  },
  {
    name: "Book Drive & Reading Festival",
    uid: "evt_" + crypto.randomBytes(8).toString("hex"),
    description: "Donate books and enjoy story-telling sessions, author meet-and-greets, and literacy workshops for all ages.",
    hostUsername: "vidyaprasar",
    hostName: "Vidya Prasar Samiti",
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570",
    mode: "Offline",
    address: "Pune Public Library",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    mapIframe: "https://maps.google.com/maps?q=pune+public+library&output=embed",
    platform: "",
    platformLink: "",
    startDate: new Date("2025-04-23"),
    endDate: new Date("2025-04-23"),
    startTime: new Date("2025-04-23T09:00:00"),
    endTime: new Date("2025-04-23T17:00:00"),
  },
  {
    name: "Emergency Preparedness Training",
    uid: "evt_" + crypto.randomBytes(8).toString("hex"),
    description: "Learn first aid, disaster preparedness, and emergency response skills from experienced professionals.",
    hostUsername: "aapdarahat",
    hostName: "Aapda Rahat Dal",
    coverImage: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982",
    mode: "Offline",
    address: "Red Cross Training Center",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    mapIframe: "https://maps.google.com/maps?q=ahmedabad+red+cross&output=embed",
    platform: "",
    platformLink: "",
    startDate: new Date("2025-05-30"),
    endDate: new Date("2025-05-31"),
    startTime: new Date("2025-05-30T09:00:00"),
    endTime: new Date("2025-05-31T17:00:00"),
  },
  {
    name: "Hybrid Fundraising Sangeet",
    uid: "evt_" + crypto.randomBytes(8).toString("hex"),
    description: "Live music concert with popular artists. Attend in-person or stream online. All proceeds benefit animal welfare.",
    hostUsername: "jivdaya",
    hostName: "Jiv Daya Sanstha",
    coverImage: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4",
    mode: "Offline",
    address: "Music Academy",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    mapIframe: "https://maps.google.com/maps?q=music+academy+chennai&output=embed",
    platform: "YouTube Live",
    platformLink: "https://youtube.com/live/concert2025",
    startDate: new Date("2025-08-20"),
    endDate: new Date("2025-08-20"),
    startTime: new Date("2025-08-20T19:00:00"),
    endTime: new Date("2025-08-20T22:00:00"),
  },
];

// Seed data for Products (Shop)
const productsData = [
  {
    productType: "Apparel",
    productName: "Khadi Cotton Kurta",
    productPrice: 1200,
    productDescription: "100% organic khadi cotton kurta. Sustainable production, supporting local weavers.",
    productImage: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
    productQty: 150,
    productSlug: "khadi-cotton-kurta",
  },
  {
    productType: "Accessories",
    productName: "Bamboo Water Bottle",
    productPrice: 450,
    productDescription: "Stylish bamboo exterior with stainless steel interior. Keeps drinks hot/cold for 12 hours. Leak-proof design.",
    productImage: "https://images.unsplash.com/photo-1602143407151-7111542de6e8",
    productQty: 200,
    productSlug: "bamboo-water-bottle",
  },
  {
    productType: "Home",
    productName: "Jute Tote Bag",
    productPrice: 250,
    productDescription: "Durable tote bag made from eco-friendly jute. Large capacity, washable, and eco-conscious.",
    productImage: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7",
    productQty: 300,
    productSlug: "jute-tote-bag",
  },
  {
    productType: "Books",
    productName: "Panchatantra Tales Bundle",
    productPrice: 800,
    productDescription: "Set of 5 illustrated educational books for children. Covers moral stories and Indian culture.",
    productImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794",
    productQty: 100,
    productSlug: "panchatantra-tales-bundle",
  },
  {
    productType: "Accessories",
    productName: "Solar-Powered Phone Charger",
    productPrice: 1500,
    productDescription: "Portable solar charger with 20000mAh battery. Perfect for outdoor activities and emergency backup.",
    productImage: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5",
    productQty: 80,
    productSlug: "solar-phone-charger",
  },
  {
    productType: "Apparel",
    productName: "Asha Bal Vikas Hoodie",
    productPrice: 999,
    productDescription: "Comfortable pullover hoodie featuring Asha Bal Vikas logo. Unisex sizing, ethically manufactured.",
    productImage: "https://images.unsplash.com/photo-1556821840-3a63f95609a7",
    productQty: 120,
    productSlug: "asha-bal-vikas-hoodie",
  },
  {
    productType: "Home",
    productName: "Handcrafted Kulhad Set",
    productPrice: 400,
    productDescription: "Set of 6 artisan-made clay kulhads. Created by local potters, supporting community development.",
    productImage: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d",
    productQty: 90,
    productSlug: "handcrafted-kulhad-set",
  },
  {
    productType: "Accessories",
    productName: "Sandalwood Bead Bracelet",
    productPrice: 300,
    productDescription: "Handwoven bracelet made from sustainable sandalwood beads. Each purchase helps protect forests.",
    productImage: "https://images.unsplash.com/photo-1611652022419-a9419f74343a",
    productQty: 250,
    productSlug: "sandalwood-bracelet",
  },
  {
    productType: "Stationery",
    productName: "Handmade Paper Notebook",
    productPrice: 200,
    productDescription: "A5 notebook made from 100% recycled handmade paper. Includes inspirational quotes.",
    productImage: "https://images.unsplash.com/photo-1531346878377-a5be20888e57",
    productQty: 200,
    productSlug: "handmade-paper-notebook",
  },
  {
    productType: "Accessories",
    productName: "Assam Tea Gift Set",
    productPrice: 750,
    productDescription: "Premium tea from Assam gardens. Includes 3 unique blends supporting farming communities.",
    productImage: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e",
    productQty: 60,
    productSlug: "assam-tea-set",
  },
  {
    productType: "Apparel",
    productName: "Nirmal Jal Cap",
    productPrice: 350,
    productDescription: "Breathable cotton cap with embroidered logo. Perfect for outdoor volunteering and showing your support.",
    productImage: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b",
    productQty: 180,
    productSlug: "nirmal-jal-cap",
  },
  {
    productType: "Toys",
    productName: "Wooden Puzzle Kit",
    productPrice: 600,
    productDescription: "Traditional wooden puzzle kit. Encourages logical thinking and patience.",
    productImage: "https://images.unsplash.com/photo-1587654780291-39c9404d746b",
    productQty: 70,
    productSlug: "wooden-puzzle-kit",
  },
];

module.exports = {
  clubsData,
  eventsData,
  productsData,
  createHash,
  randomDate,
};